// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, TrackEvent) {
  TrackEventView = 0,
  TrackEventCategory = 1,
  TrackEventCart = 2,
  TrackEventRemove_from_cart = 3,
  TrackEventPurchase = 4,
  TrackEventSearch = 5,
  TrackEventWish = 6,
  TrackEventRemove_wish = 7,
};

/// Wrapper for TrackEvent to allow for nullability.
@interface TrackEventBox : NSObject
@property(nonatomic, assign) TrackEvent value;
- (instancetype)initWithValue:(TrackEvent)value;
@end


/// The codec used by Rees46Sender.
NSObject<FlutterMessageCodec> *Rees46SenderGetCodec(void);

/// FLUTTER FRAMEWORK -> FLUTTER ENGINE
@protocol Rees46Sender
- (void)initializeShopID:(NSString *)shopID apiDomain:(nullable NSString *)apiDomain token:(nullable NSString *)token error:(FlutterError *_Nullable *_Nonnull)error;
- (void)trackTrackEvent:(NSString *)trackEvent itemID:(NSString *)itemID amount:(nullable NSNumber *)amount error:(FlutterError *_Nullable *_Nonnull)error;
- (void)recommendRecommenderCode:(NSString *)recommenderCode extended:(BOOL)extended itemID:(NSString *)itemID categoryID:(NSString *)categoryID completion:(void (^)(NSArray<NSString *> *_Nullable, FlutterError *_Nullable))completion;
- (void)setProfileUserId:(NSString *)userId email:(NSString *)email phone:(NSString *)phone error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpRees46Sender(id<FlutterBinaryMessenger> binaryMessenger, NSObject<Rees46Sender> *_Nullable api);

extern void SetUpRees46SenderWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<Rees46Sender> *_Nullable api, NSString *messageChannelSuffix);

/// The codec used by Rees46Receiver.
NSObject<FlutterMessageCodec> *Rees46ReceiverGetCodec(void);

/// FLUTTER FRAMEWORK <- FLUTTER ENGINE
@interface Rees46Receiver : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
@end

NS_ASSUME_NONNULL_END
